module.exports = {
  components: {
    categories: [
      {
        name: "TypeScript components",
        include: [],
      },
      {
        name: "Components",
        include: [
          "src/components/Accordion/Accordion.tsx",
          "src/components/AccordionGroup/AccordionGroup.tsx",
          "src/components/AccordionGroupItem/AccordionGroupItem.tsx",
          "src/components/BulletedList/BulletedList.tsx",
          "src/components/BulletedListItem/BulletedListItem.tsx",
          "src/components/Button/Button.tsx",
          "src/components/Card/Card.tsx",
          "src/components/Checkbox/Checkbox.tsx",
          "src/components/Chip/Chip.tsx",
          "src/components/DateInput/DateInput.tsx",
          "src/components/Flex/Flex.tsx",
          "src/components/Heading/Heading.tsx",
          "src/components/Link/Link.tsx",
          "src/components/Select/Select.tsx",
          "src/components/TextInput/TextInput.tsx",
          "src/components/ToggleGroup/ToggleGroup.tsx",
          "src/components/ThemeCustomizer/ThemeCustomizer.js",
          "src/components/Typography/Typography.tsx",
        ],
      },
      {
        name: "Layout",
        include: [
          "src/components/ApplicationLayout/ApplicationLayout.tsx",
          "src/components/Bleed/Bleed.tsx",
          "src/components/Box/Box.tsx",
          "src/components/Dialog/Dialog.tsx",
          "src/components/Footer/Footer.tsx",
          "src/components/Header/Header.tsx",
          "src/components/Inset/Inset.tsx",
          "src/components/Sidenav/Sidenav.tsx",
          "src/components/SidenavTitle/SidenavTitle.tsx",
          "src/components/SidenavSection/SidenavSection.tsx",
          "src/components/SidenavGroup/SidenavGroup.tsx",
          "src/components/SidenavLink/SidenavLink.tsx",
        ],
      },
    ],
    wrapper: "src/components/UXPinWrapper/UXPinWrapper.js",
    webpackConfig: "webpack.config.js",
  },
  name: "DXC Halstack Design System",
};
